/* ClaudeAmp - RADIO station playlists: top songs of 1990-1999 per station,
   assembled from surviving station countdowns/charts (KROQ Top 106.7, WBRU
   year-end lists, CMJ college charts, Billboard format airplay) filled out
   with each station's verifiable format canon. College stations carry the
   underground/CMJ canon only - no chart-topping superstar acts. Tracks ship
   as artist+title; the player resolves each to its lowest-view YouTube
   upload through the bridge search on first play. */
"use strict";

window.RADIO_STATIONS = [
  { call: "WBRU", name: "95.5 WBRU PROVIDENCE", format: "ALTERNATIVE ROCK", tracks: [
    { a: "Morphine", t: "Buena" },
    { a: "Toad the Wet Sprocket", t: "Walk on the Ocean" },
    { a: "Ben Folds Five", t: "Underground" },
    { a: "Fugazi", t: "Repeater" },
    { a: "Harvey Danger", t: "Flagpole Sitta" },
    { a: "Gin Blossoms", t: "Hey Jealousy" },
    { a: "Buffalo Tom", t: "Taillights Fade" },
    { a: "Soul Coughing", t: "Super Bon Bon" },
    { a: "Superdrag", t: "Sucked Out" },
    { a: "Juliana Hatfield Three", t: "My Sister" },
    { a: "Better Than Ezra", t: "Good" },
    { a: "Marcy Playground", t: "Sex and Candy" },
    { a: "Tribe", t: "Joyride (I Saw the Film)" },
    { a: "Catherine Wheel", t: "Black Metallic" },
    { a: "Digable Planets", t: "Rebirth of Slick (Cool Like Dat)" },
    { a: "Luscious Jackson", t: "Naked Eye" },
    { a: "Local H", t: "Bound for the Floor" },
    { a: "Fountains of Wayne", t: "Radiation Vibe" },
    { a: "Throwing Muses", t: "Counting Backwards" },
    { a: "Pixies", t: "Velouria" },
    { a: "Less Than Jake", t: "Al's War" },
    { a: "Cracker", t: "Low" },
    { a: "Everclear", t: "Santa Monica" },
    { a: "Placebo", t: "Pure Morning" },
    { a: "Eels", t: "Novocaine for the Soul" },
    { a: "Fugazi", t: "Merchandise" },
    { a: "Sebadoh", t: "Rebound" },
    { a: "Morphine", t: "Honey White" },
    { a: "Belly", t: "Now They'll Sleep" },
    { a: "Buffalo Tom", t: "Sodajerk" },
    { a: "Juliana Hatfield", t: "Spin the Bottle" },
    { a: "Dinosaur Jr.", t: "Start Choppin" },
    { a: "Throwing Muses", t: "Bright Yellow Gun" },
    { a: "Weezer", t: "Buddy Holly" },
    { a: "Supergrass", t: "Alright" },
    { a: "Shudder to Think", t: "X-French Tee Shirt" },
    { a: "Luna", t: "23 Minutes in Brussels" },
    { a: "Smoking Popes", t: "Need You Around" },
    { a: "Heather Nova", t: "Walk This World" },
    { a: "The Innocence Mission", t: "Bright as Yellow" },
    { a: "Tripping Daisy", t: "I Got a Girl" },
    { a: "The Bogmen", t: "Suddenly" },
    { a: "The Posies", t: "Dream All Day" },
    { a: "Matthew Sweet", t: "Sick of Myself" },
    { a: "The Afghan Whigs", t: "Gentlemen" },
    { a: "PJ Harvey", t: "Down by the Water" },
    { a: "Blur", t: "Song 2" },
    { a: "James", t: "Laid" },
    { a: "Ned's Atomic Dustbin", t: "Grey Cell Green" },
    { a: "The Sundays", t: "Here's Where the Story Ends" },
    { a: "Ride", t: "Vapour Trail" },
    { a: "Lush", t: "For Love" },
    { a: "The Cardigans", t: "Been It" },
    { a: "Sponge", t: "Plowed" },
    { a: "Collective Soul", t: "Shine" },
    { a: "Nada Surf", t: "Popular" },
    { a: "The Rentals", t: "Friends of P." },
    { a: "Veruca Salt", t: "Seether" },
    { a: "K's Choice", t: "Not an Addict" },
    { a: "Stabbing Westward", t: "Shame" },
    { a: "Black Lab", t: "Wash It Away" },
    { a: "The Flys", t: "Got You (Where I Want You)" },
    { a: "Fuel", t: "Shimmer" },
    { a: "Our Lady Peace", t: "Clumsy" },
    { a: "Guster", t: "Airport Song" },
    { a: "Beth Orton", t: "Stolen Car" },
    { a: "Ben Harper", t: "Ground on Down" },
    { a: "Fun Lovin' Criminals", t: "Scooby Snacks" },
    { a: "Goldfinger", t: "Here in Your Bedroom" },
    { a: "Save Ferris", t: "The World Is New" },
    { a: "Dance Hall Crashers", t: "Lost Again" },
    { a: "Rancid", t: "Ruby Soho" },
    { a: "The Aquabats", t: "Super Rad!" },
    { a: "NOFX", t: "Linoleum" },
    { a: "Bad Religion", t: "21st Century (Digital Boy)" },
    { a: "Jawbreaker", t: "Fireman" },
    { a: "The Suicide Machines", t: "New Girl" },
    { a: "Reel Big Fish", t: "Sell Out" },
    { a: "Primus", t: "Wynona's Big Brown Beaver" },
    { a: "Helmet", t: "Unsung" },
    { a: "Quicksand", t: "Dine Alone" },
    { a: "Failure", t: "Stuck on You" },
    { a: "Hum", t: "Stars" },
    { a: "Jawbox", t: "Savory" },
    { a: "Guided by Voices", t: "Game of Pricks" },
    { a: "Archers of Loaf", t: "Web in Front" },
    { a: "Pavement", t: "Cut Your Hair" },
    { a: "The Chemical Brothers", t: "Block Rockin' Beats" },
    { a: "The Chemical Brothers", t: "Let Forever Be" },
    { a: "The Prodigy", t: "Firestarter" },
    { a: "Propellerheads", t: "History Repeating" },
    { a: "Fatboy Slim", t: "Gangster Tripping" },
    { a: "The Crystal Method", t: "Busy Child" },
    { a: "Lo Fidelity Allstars", t: "Battle Flag" },
    { a: "Sneaker Pimps", t: "6 Underground" },
    { a: "Moby", t: "Bodyrock" },
    { a: "A Tribe Called Quest", t: "Bonita Applebum" },
    { a: "Fastball", t: "The Way" },
    { a: "The Roots", t: "What They Do" },
    { a: "Komeda", t: "Boogie Woogie / Rock 'N' Roll" },
  ] },
  { call: "KALX", name: "KALX 90.7 FM BERKELEY", format: "COLLEGE / INDIE ECLECTIC", tracks: [
    { a: "Pavement", t: "Cut Your Hair" },
    { a: "Unwound", t: "Corpse Pose" },
    { a: "Helium", t: "Pat's Trick" },
    { a: "Smog", t: "Cold Blooded Old Times" },
    { a: "Sonic Youth", t: "Bull in the Heather" },
    { a: "Cat Power", t: "Nude as the News" },
    { a: "Pixies", t: "Velouria" },
    { a: "Girls Against Boys", t: "Kill the Sexplayer" },
    { a: "My Bloody Valentine", t: "Only Shallow" },
    { a: "The Charlatans", t: "The Only One I Know" },
    { a: "The Sundays", t: "Here's Where the Story Ends" },
    { a: "Mazzy Star", t: "Fade Into You" },
    { a: "PJ Harvey", t: "Down by the Water" },
    { a: "Dinosaur Jr", t: "Feel the Pain" },
    { a: "Stereolab", t: "Ping Pong" },
    { a: "Mercury Rev", t: "Goddess on a Hiway" },
    { a: "Bjork", t: "Human Behaviour" },
    { a: "Portishead", t: "Sour Times" },
    { a: "Sonic Youth", t: "Kool Thing" },
    { a: "Liz Phair", t: "Never Said" },
    { a: "Pavement", t: "Gold Soundz" },
    { a: "Guided by Voices", t: "I Am a Scientist" },
    { a: "Superchunk", t: "Slack Motherfucker" },
    { a: "Archers of Loaf", t: "Web in Front" },
    { a: "Sebadoh", t: "Rebound" },
    { a: "Yo La Tengo", t: "Autumn Sweater" },
    { a: "DJ Shadow", t: "Midnight in a Perfect World" },
    { a: "Souls of Mischief", t: "93 'til Infinity" },
    { a: "Del the Funky Homosapien", t: "Mistadobalina" },
    { a: "Screeching Weasel", t: "Cool Kids" },
    { a: "Uncle Tupelo", t: "Gun" },
    { a: "They Might Be Giants", t: "Birdhouse in Your Soul" },
    { a: "The Magnetic Fields", t: "Strange Powers" },
    { a: "Kitchens of Distinction", t: "Drive That Fast" },
    { a: "Morrissey", t: "November Spawned a Monster" },
    { a: "Happy Mondays", t: "Step On" },
    { a: "The Stone Roses", t: "Fools Gold" },
    { a: "Ride", t: "Vapour Trail" },
    { a: "Lush", t: "Sweetness and Light" },
    { a: "Cocteau Twins", t: "Iceblink Luck" },
    { a: "Slowdive", t: "Alison" },
    { a: "Throwing Muses", t: "Counting Backwards" },
    { a: "Teenage Fanclub", t: "The Concept" },
    { a: "Matthew Sweet", t: "Girlfriend" },
    { a: "Sugar", t: "If I Can't Change Your Mind" },
    { a: "Belly", t: "Feed the Tree" },
    { a: "The Lemonheads", t: "It's a Shame About Ray" },
    { a: "The Flaming Lips", t: "She Don't Use Jelly" },
    { a: "Ween", t: "Push th' Little Daisies" },
    { a: "Company Flow", t: "8 Steps to Perfection" },
    { a: "A Tribe Called Quest", t: "Scenario" },
    { a: "De La Soul", t: "Ring Ring Ring (Ha Ha Hey)" },
    { a: "Hieroglyphics", t: "You Never Knew" },
    { a: "The Pharcyde", t: "Passin' Me By" },
    { a: "The Coup", t: "Fat Cats, Bigga Fish" },
    { a: "Latyrx", t: "Lady Don't Tek No" },
    { a: "Blackalicious", t: "Alphabet Aerobics" },
    { a: "Black Star", t: "Definition" },
    { a: "Dr. Octagon", t: "Blue Flowers" },
    { a: "Disposable Heroes of Hiphoprisy", t: "Television, the Drug of the Nation" },
    { a: "Massive Attack", t: "Unfinished Sympathy" },
    { a: "Tom Waits", t: "Goin' Out West" },
    { a: "Nick Cave and the Bad Seeds", t: "Red Right Hand" },
    { a: "Morphine", t: "Cure for Pain" },
    { a: "The Jon Spencer Blues Explosion", t: "Bellbottoms" },
    { a: "Bikini Kill", t: "Rebel Girl" },
    { a: "Sleater-Kinney", t: "Dig Me Out" },
    { a: "Bratmobile", t: "Cool Schmool" },
    { a: "L7", t: "Pretend We're Dead" },
    { a: "Team Dresch", t: "Hate the Christian Right!" },
    { a: "Mudhoney", t: "Suck You Dry" },
    { a: "Fugazi", t: "Merchandise" },
    { a: "Jawbreaker", t: "Boxcar" },
    { a: "Operation Ivy", t: "Sound System" },
    { a: "Swingin' Utters", t: "Five Lessons Learned" },
    { a: "The Queers", t: "Don't Back Down" },
    { a: "The Mr. T Experience", t: "Even Hitler Had a Girlfriend" },
    { a: "Pansy Division", t: "Fem in a Black Leather Jacket" },
    { a: "Thinking Fellers Union Local 282", t: "Hurricane" },
    { a: "The Jesus Lizard", t: "Puss" },
    { a: "Swervedriver", t: "Duel" },
    { a: "Drive Like Jehu", t: "Here Come the Rome Plows" },
    { a: "Built to Spill", t: "Carry the Zero" },
    { a: "Modest Mouse", t: "Doin' the Cockroach" },
    { a: "Neutral Milk Hotel", t: "Holland, 1945" },
    { a: "Elliott Smith", t: "Needle in the Hay" },
    { a: "Elliott Smith", t: "Waltz #2 (XO)" },
    { a: "Belle and Sebastian", t: "The Boy with the Arab Strap" },
    { a: "Yo La Tengo", t: "Sugarcube" },
    { a: "Stereolab", t: "French Disko" },
    { a: "Slint", t: "Good Morning, Captain" },
    { a: "Galaxie 500", t: "Fourth of July" },
    { a: "Red House Painters", t: "Katy Song" },
    { a: "American Music Club", t: "Johnny Mathis' Feet" },
    { a: "Silver Jews", t: "Random Rules" },
    { a: "Spiritualized", t: "Ladies and Gentlemen We Are Floating in Space" },
    { a: "Cornershop", t: "Brimful of Asha" },
    { a: "Cibo Matto", t: "Know Your Chicken" },
    { a: "Elastica", t: "Connection" },
    { a: "Pulp", t: "Common People" },
  ] },
  { call: "KEXP", name: "KEXP SEATTLE (KCMU IN THE 90S)", format: "SEATTLE INDIE / ALTERNATIVE", tracks: [
    { a: "Mudhoney", t: "Suck You Dry" },
    { a: "Modest Mouse", t: "Dramamine" },
    { a: "Rocket from the Crypt", t: "On a Rope" },
    { a: "Sonic Youth", t: "Kool Thing" },
    { a: "Mazzy Star", t: "Fade Into You" },
    { a: "Bikini Kill", t: "Rebel Girl" },
    { a: "Sunny Day Real Estate", t: "Seven" },
    { a: "Red House Painters", t: "Katy Song" },
    { a: "A Tribe Called Quest", t: "Can I Kick It?" },
    { a: "Elliott Smith", t: "Needle in the Hay" },
    { a: "Tad", t: "Jack Pepsi" },
    { a: "Stereolab", t: "Cybele's Reverie" },
    { a: "Massive Attack", t: "Teardrop" },
    { a: "Built to Spill", t: "Carry the Zero" },
    { a: "Mother Love Bone", t: "Chloe Dancer/Crown of Thorns" },
    { a: "Sebadoh", t: "Soul and Fire" },
    { a: "Unwound", t: "Corpse Pose" },
    { a: "Low", t: "Over the Ocean" },
    { a: "Neutral Milk Hotel", t: "In the Aeroplane Over the Sea" },
    { a: "Pavement", t: "Gold Soundz" },
    { a: "Cat Power", t: "Nude as the News" },
    { a: "Sunny Day Real Estate", t: "In Circles" },
    { a: "Smog", t: "Cold Blooded Old Times" },
    { a: "Guided by Voices", t: "I Am a Scientist" },
    { a: "Massive Attack", t: "Protection" },
    { a: "Jeff Buckley", t: "Lover, You Should Have Come Over" },
    { a: "Bjork", t: "Army of Me" },
    { a: "Superchunk", t: "Hyper Enough" },
    { a: "Guided by Voices", t: "Motor Away" },
    { a: "The Stone Roses", t: "I Wanna Be Adored" },
    { a: "Stereolab", t: "Ping Pong" },
    { a: "Stereolab", t: "French Disko" },
    { a: "Sleater-Kinney", t: "Little Babies" },
    { a: "Mudhoney", t: "Let It Slide" },
    { a: "Wu-Tang Clan", t: "C.R.E.A.M." },
    { a: "DJ Shadow", t: "Midnight in a Perfect World" },
    { a: "Seaweed", t: "Kid Candy" },
    { a: "Love Battery", t: "Out of Focus" },
    { a: "Cocteau Twins", t: "Heaven or Las Vegas" },
    { a: "Jeff Buckley", t: "Last Goodbye" },
    { a: "Tortoise", t: "Djed" },
    { a: "They Might Be Giants", t: "Birdhouse in Your Soul" },
    { a: "Le Tigre", t: "Deceptacon" },
    { a: "Massive Attack", t: "Unfinished Sympathy" },
    { a: "Superchunk", t: "Slack Motherfucker" },
    { a: "Billy Bragg and Wilco", t: "California Stars" },
    { a: "My Bloody Valentine", t: "Only Shallow" },
    { a: "Aphex Twin", t: "Windowlicker" },
    { a: "The Posies", t: "Dream All Day" },
    { a: "The Magnetic Fields", t: "Papa Was a Rodeo" },
    { a: "Daft Punk", t: "Around the World" },
    { a: "Bjork", t: "Hyperballad" },
    { a: "Pavement", t: "Summer Babe" },
    { a: "A Tribe Called Quest", t: "Electric Relaxation" },
    { a: "Cat Power", t: "Cross Bones Style" },
    { a: "Elliott Smith", t: "Waltz #2 (XO)" },
    { a: "Pulp", t: "Common People" },
    { a: "Neutral Milk Hotel", t: "Holland, 1945" },
    { a: "Yo La Tengo", t: "Tom Courtenay" },
    { a: "Yo La Tengo", t: "Autumn Sweater" },
    { a: "The Pharcyde", t: "Passin' Me By" },
    { a: "Screaming Trees", t: "Nearly Lost You" },
    { a: "Sigur Ros", t: "Svefn-g-englar" },
    { a: "Black Star", t: "Definition" },
    { a: "Built to Spill", t: "Big Dipper" },
    { a: "Elliott Smith", t: "Angeles" },
    { a: "Brad", t: "The Day Brings" },
    { a: "Beat Happening", t: "Red Head Walking" },
    { a: "The Beta Band", t: "Dry the Rain" },
    { a: "Portishead", t: "Glory Box" },
    { a: "Del the Funky Homosapien", t: "Mistadobalina" },
    { a: "Liz Phair", t: "Never Said" },
    { a: "Murder City Devils", t: "Press Gang" },
    { a: "Guided by Voices", t: "Game of Pricks" },
    { a: "Pavement", t: "Cut Your Hair" },
    { a: "Archers of Loaf", t: "Web in Front" },
    { a: "Sebadoh", t: "Rebound" },
    { a: "Belle and Sebastian", t: "The State I Am In" },
    { a: "PJ Harvey", t: "Sheela-Na-Gig" },
    { a: "Tricky", t: "Black Steel" },
    { a: "My Bloody Valentine", t: "Soon" },
    { a: "Built to Spill", t: "Car" },
    { a: "Slint", t: "Good Morning, Captain" },
    { a: "Sleater-Kinney", t: "Dig Me Out" },
    { a: "Mercury Rev", t: "Goddess on a Hiway" },
    { a: "Jeff Buckley", t: "Grace" },
    { a: "Sleater-Kinney", t: "One More Hour" },
    { a: "Portishead", t: "Sour Times" },
    { a: "PJ Harvey", t: "Rid of Me" },
    { a: "Hooverphonic", t: "2 Wicky" },
    { a: "Throwing Muses", t: "Not Too Soon" },
    { a: "The Jesus Lizard", t: "Puss" },
    { a: "Slowdive", t: "Alison" },
    { a: "Heatmiser", t: "Plainclothes Man" },
    { a: "Tricky", t: "Overcome" },
    { a: "Unwound", t: "Dragnalus" },
    { a: "Souls of Mischief", t: "93 'Til Infinity" },
    { a: "Silver Jews", t: "Random Rules" },
    { a: "Modest Mouse", t: "Doin' the Cockroach" },
    { a: "A Tribe Called Quest", t: "Buggin' Out" },
  ] },
  { call: "KFJC", name: "KFJC 89.7 LOS ALTOS HILLS", format: "BAY AREA FREEFORM", tracks: [
    { a: "The Mermen", t: "Pulpin' Line" },
    { a: "Thinking Fellers Union Local 282", t: "Sister Hell" },
    { a: "Man or Astro-man?", t: "Sferic Waves" },
    { a: "Sun City Girls", t: "Space Prophet Dogon" },
    { a: "Dick Dale", t: "Nitro" },
    { a: "Melt-Banana", t: "Mouse Is a Biscuit" },
    { a: "Trumans Water", t: "Aroma of Gina Arnold" },
    { a: "The Brian Jonestown Massacre", t: "Anemone" },
    { a: "Melvins", t: "Honey Bucket" },
    { a: "Merzbow", t: "Woodpecker No. 1" },
    { a: "The Mummies", t: "(You Must Fight to Live) On the Planet of the Apes" },
    { a: "Boredoms", t: "Acid Police" },
    { a: "The Aqua Velvets", t: "Martini Time" },
    { a: "Negativland", t: "U2" },
    { a: "The Bevis Frond", t: "He'd Be a Diamond" },
    { a: "Windy and Carl", t: "Antarctica" },
    { a: "Cluster", t: "One Hour" },
    { a: "Spazz", t: "4X a Day" },
    { a: "The Trashwomen", t: "Justine" },
    { a: "Wesley Willis", t: "Rock N Roll McDonald's" },
    { a: "The Mermen", t: "The Drowning Man Knows His God" },
    { a: "Man or Astro-man?", t: "Transmissions from Venus" },
    { a: "Dick Dale", t: "Scalped" },
    { a: "Farflung", t: "Candied Electronic Atmospheres" },
    { a: "Melt-Banana", t: "Sick Zip Everywhere" },
    { a: "Sun City Girls", t: "The Shining Path" },
    { a: "Neurosis", t: "Locust Star" },
    { a: "Sleep", t: "Dragonaut" },
    { a: "Mr. Bungle", t: "Desert Search for Techno Allah" },
    { a: "Thinking Fellers Union Local 282", t: "Hurricane" },
    { a: "Barbara Manning's SF Seals", t: "Dock Ellis" },
    { a: "The Loud Family", t: "Aerodeliria" },
    { a: "Tarnation", t: "Game of Broken Hearts" },
    { a: "Red House Painters", t: "Katy Song" },
    { a: "DJ Shadow", t: "In/Flux" },
    { a: "Dr. Octagon", t: "Blue Flowers" },
    { a: "Invisibl Skratch Piklz", t: "Invasion of the Octopus People" },
    { a: "Latyrx", t: "Latyrx" },
    { a: "Deerhoof", t: "Gore in Rut" },
    { a: "Pavement", t: "Summer Babe" },
    { a: "Tom Waits", t: "Goin' Out West" },
    { a: "Helios Creed", t: "Lactating Purple" },
    { a: "Melvins", t: "Boris" },
    { a: "Stereolab", t: "French Disko" },
    { a: "Sonic Youth", t: "The Diamond Sea" },
    { a: "Sebadoh", t: "Gimme Indie Rock" },
    { a: "Guided by Voices", t: "I Am a Scientist" },
    { a: "Polvo", t: "Vibracobra" },
    { a: "Unwound", t: "Corpse Pose" },
    { a: "Shellac", t: "My Black Ass" },
    { a: "The Jesus Lizard", t: "Puss" },
    { a: "Slint", t: "Good Morning, Captain" },
    { a: "The Fall", t: "Free Range" },
    { a: "Superchunk", t: "Slack Motherfucker" },
    { a: "Archers of Loaf", t: "Web in Front" },
    { a: "Bikini Kill", t: "Rebel Girl" },
    { a: "Sleater-Kinney", t: "Dig Me Out" },
    { a: "Fugazi", t: "Merchandise" },
    { a: "Six Finger Satellite", t: "Rabies (Baby's Got The)" },
    { a: "Brainiac", t: "Vincent Come On Down" },
    { a: "Ween", t: "Push th' Little Daisies" },
    { a: "King Missile", t: "Detachable Penis" },
    { a: "Elliott Smith", t: "Needle in the Hay" },
    { a: "Daniel Johnston", t: "Life in Vain" },
    { a: "Palace Brothers", t: "Ohio River Boat Song" },
    { a: "Smog", t: "Cold Blooded Old Times" },
    { a: "Neutral Milk Hotel", t: "Holland, 1945" },
    { a: "The Olivia Tremor Control", t: "Jumping Fences" },
    { a: "Mercury Rev", t: "Car Wash Hair" },
    { a: "My Bloody Valentine", t: "Only Shallow" },
    { a: "Spiritualized", t: "Ladies and Gentlemen We Are Floating in Space" },
    { a: "Flying Saucer Attack", t: "Land Beyond the Sun" },
    { a: "Labradford", t: "Accelerating on a Smoother Road" },
    { a: "Bardo Pond", t: "Tommy Gun Angel" },
    { a: "Godspeed You Black Emperor", t: "East Hastings" },
    { a: "Tortoise", t: "Djed" },
    { a: "Tortoise", t: "Gamera" },
    { a: "Gastr del Sol", t: "Our Exquisite Replica of Eternity" },
    { a: "Jim O'Rourke", t: "Women of the World" },
    { a: "Low", t: "Words" },
    { a: "Aphex Twin", t: "Didgeridoo" },
    { a: "Autechre", t: "Bike" },
    { a: "Oval", t: "Do While" },
    { a: "Squarepusher", t: "Come On My Selector" },
    { a: "Naked City", t: "Batman" },
    { a: "Zeni Geva", t: "Desire for Agony" },
    { a: "Ruins", t: "Hyderomastgroningem" },
    { a: "Acid Mothers Temple", t: "Speed Guru" },
    { a: "Boredoms", t: "Super Are" },
    { a: "Guitar Wolf", t: "Missile Me" },
    { a: "Southern Culture on the Skids", t: "Camel Walk" },
    { a: "Reverend Horton Heat", t: "Psychobilly Freakout" },
    { a: "Los Straitjackets", t: "Caveman" },
    { a: "Shadowy Men on a Shadowy Planet", t: "Having an Average Weekend" },
    { a: "Combustible Edison", t: "Blue Light" },
    { a: "Esquivel", t: "Mucha Muchacha" },
    { a: "The Dead C", t: "Bad Politics" },
    { a: "Beat Happening", t: "Red Head Walking" },
    { a: "Bongwater", t: "Nick Cave Dolls" },
    { a: "Stereolab", t: "Metronomic Underground" },
  ] },
  { call: "WDOM", name: "WDOM 91.3 PROVIDENCE", format: "COLLEGE ALTERNATIVE", tracks: [
    { a: "Unwound", t: "Corpse Pose" },
    { a: "Pavement", t: "Cut Your Hair" },
    { a: "Silver Jews", t: "Random Rules" },
    { a: "Chavez", t: "Break Up Your Band" },
    { a: "Smog", t: "Cold Blooded Old Times" },
    { a: "The Spinanes", t: "Noel, Jonah and Me" },
    { a: "Belly", t: "Feed the Tree" },
    { a: "Pixies", t: "Velouria" },
    { a: "Sonic Youth", t: "Kool Thing" },
    { a: "Throwing Muses", t: "Bright Yellow Gun" },
    { a: "The Halo Benders", t: "Virginia Reel Around the Fountain" },
    { a: "PJ Harvey", t: "Down by the Water" },
    { a: "Polvo", t: "Tilebreaker" },
    { a: "Liz Phair", t: "Never Said" },
    { a: "Guided by Voices", t: "I Am a Scientist" },
    { a: "Neutral Milk Hotel", t: "Holland, 1945" },
    { a: "Yo La Tengo", t: "Autumn Sweater" },
    { a: "Elliott Smith", t: "Waltz #2 (XO)" },
    { a: "Built to Spill", t: "Carry the Zero" },
    { a: "Superchunk", t: "Slack Motherfucker" },
    { a: "Drive Like Jehu", t: "Here Come the Rome Plows" },
    { a: "Slint", t: "Good Morning, Captain" },
    { a: "Pavement", t: "Summer Babe" },
    { a: "Black Star", t: "Definition" },
    { a: "Bjork", t: "Human Behaviour" },
    { a: "Portishead", t: "Sour Times" },
    { a: "Mazzy Star", t: "Fade Into You" },
    { a: "The Sundays", t: "Here's Where the Story Ends" },
    { a: "My Bloody Valentine", t: "Only Shallow" },
    { a: "Dinosaur Jr", t: "Feel the Pain" },
    { a: "Sebadoh", t: "Skull" },
    { a: "Buffalo Tom", t: "Taillights Fade" },
    { a: "Morphine", t: "Cure for Pain" },
    { a: "The Lemonheads", t: "It's a Shame About Ray" },
    { a: "Come", t: "Fast Piss Blues" },
    { a: "Rocket from the Crypt", t: "On a Rope" },
    { a: "A Tribe Called Quest", t: "Scenario" },
    { a: "Digable Planets", t: "Rebirth of Slick (Cool Like Dat)" },
    { a: "Wu-Tang Clan", t: "C.R.E.A.M." },
    { a: "Pulp", t: "Common People" },
    { a: "Shellac", t: "My Black Ass" },
    { a: "Mercury Rev", t: "Car Wash Hair" },
    { a: "Low", t: "Words" },
    { a: "Cocteau Twins", t: "Heaven or Las Vegas" },
    { a: "Ride", t: "Vapour Trail" },
    { a: "Lush", t: "For Love" },
    { a: "Elastica", t: "Connection" },
    { a: "Galaxie 500", t: "Fourth of July" },
    { a: "Luna", t: "Tiger Lily" },
    { a: "Spiritualized", t: "Ladies and Gentlemen We Are Floating in Space" },
    { a: "The Flaming Lips", t: "She Don't Use Jelly" },
    { a: "Ween", t: "Push th' Little Daisies" },
    { a: "They Might Be Giants", t: "Birdhouse in Your Soul" },
    { a: "Violent Femmes", t: "American Music" },
    { a: "Fugazi", t: "Waiting Room" },
    { a: "Jawbox", t: "Savory" },
    { a: "Sunny Day Real Estate", t: "In Circles" },
    { a: "Archers of Loaf", t: "Web in Front" },
    { a: "Sleater-Kinney", t: "Dig Me Out" },
    { a: "Bikini Kill", t: "Rebel Girl" },
    { a: "Veruca Salt", t: "Seether" },
    { a: "The Juliana Hatfield Three", t: "My Sister" },
    { a: "Letters to Cleo", t: "Here and Now" },
    { a: "Velvet Crush", t: "Hold Me Up" },
    { a: "Scarce", t: "All Sideways" },
    { a: "Six Finger Satellite", t: "Parlour Games" },
    { a: "Combustible Edison", t: "Blue Light" },
    { a: "Helium", t: "Pat's Trick" },
    { a: "Throwing Muses", t: "Counting Backwards" },
    { a: "The Magnetic Fields", t: "Strange Powers" },
    { a: "Palace Brothers", t: "Ohio River Boat Song" },
    { a: "Seam", t: "Rafael" },
    { a: "Codeine", t: "Sea" },
    { a: "Tortoise", t: "Djed" },
    { a: "The Apples in Stereo", t: "Tidal Wave" },
    { a: "Belly", t: "Gepetto" },
    { a: "Pixies", t: "Dig for Fire" },
    { a: "Sonic Youth", t: "Bull in the Heather" },
    { a: "The Sea and Cake", t: "Parasol" },
    { a: "PJ Harvey", t: "Sheela-Na-Gig" },
    { a: "Bjork", t: "Hyperballad" },
    { a: "Elliott Smith", t: "Between the Bars" },
    { a: "Guided by Voices", t: "Motor Away" },
    { a: "Built to Spill", t: "Big Dipper" },
    { a: "Pavement", t: "Gold Soundz" },
    { a: "Modest Mouse", t: "Dramamine" },
    { a: "Wilco", t: "Outtasite (Outta Mind)" },
    { a: "Uncle Tupelo", t: "The Long Cut" },
    { a: "Cat Power", t: "Nude as the News" },
    { a: "Stereolab", t: "Ping Pong" },
    { a: "Belle and Sebastian", t: "The Boy with the Arab Strap" },
    { a: "Cornershop", t: "Brimful of Asha" },
    { a: "Folk Implosion", t: "Natural One" },
    { a: "The Olivia Tremor Control", t: "Jumping Fences" },
    { a: "Massive Attack", t: "Unfinished Sympathy" },
    { a: "A Tribe Called Quest", t: "Can I Kick It?" },
    { a: "De La Soul", t: "Stakes Is High" },
    { a: "Nas", t: "The World Is Yours" },
    { a: "The Pharcyde", t: "Passin' Me By" },
    { a: "The Roots", t: "What They Do" },
  ] },
  { call: "WXBK", name: "94.7 THE BLOCK NEW YORK", format: "CLASSIC HIP-HOP / THROWBACK R&B", tracks: [
    { a: "The Notorious B.I.G.", t: "Juicy" },
    { a: "2Pac", t: "California Love" },
    { a: "Dr. Dre", t: "Nuthin' but a 'G' Thang" },
    { a: "Wu-Tang Clan", t: "C.R.E.A.M." },
    { a: "The Notorious B.I.G.", t: "Big Poppa" },
    { a: "Snoop Doggy Dogg", t: "Gin and Juice" },
    { a: "Nas", t: "If I Ruled the World (Imagine That)" },
    { a: "Jay-Z", t: "Hard Knock Life (Ghetto Anthem)" },
    { a: "Method Man", t: "I'll Be There for You / You're All I Need to Get By (feat. Mary J. Blige)" },
    { a: "Warren G", t: "Regulate (feat. Nate Dogg)" },
    { a: "Mary J. Blige", t: "Real Love" },
    { a: "The Notorious B.I.G.", t: "Hypnotize" },
    { a: "Coolio", t: "Gangsta's Paradise" },
    { a: "Blackstreet", t: "No Diggity" },
    { a: "Puff Daddy and Faith Evans", t: "I'll Be Missing You" },
    { a: "Montell Jordan", t: "This Is How We Do It" },
    { a: "TLC", t: "Waterfalls" },
    { a: "A Tribe Called Quest", t: "Scenario" },
    { a: "The Notorious B.I.G.", t: "Mo Money Mo Problems" },
    { a: "Bell Biv DeVoe", t: "Poison" },
    { a: "2Pac", t: "Dear Mama" },
    { a: "Naughty by Nature", t: "O.P.P." },
    { a: "DJ Jazzy Jeff and The Fresh Prince", t: "Summertime" },
    { a: "Fugees", t: "Killing Me Softly" },
    { a: "Ice Cube", t: "It Was a Good Day" },
    { a: "Mobb Deep", t: "Shook Ones, Pt. II" },
    { a: "LL Cool J", t: "Mama Said Knock You Out" },
    { a: "House of Pain", t: "Jump Around" },
    { a: "TLC", t: "No Scrubs" },
    { a: "DMX", t: "Ruff Ryders' Anthem" },
    { a: "Missy Elliott", t: "The Rain (Supa Dupa Fly)" },
    { a: "Lauryn Hill", t: "Doo Wop (That Thing)" },
    { a: "Busta Rhymes", t: "Put Your Hands Where My Eyes Could See" },
    { a: "Craig Mack", t: "Flava in Ya Ear" },
    { a: "Naughty by Nature", t: "Hip Hop Hooray" },
    { a: "Salt-N-Pepa", t: "Shoop" },
    { a: "SWV", t: "Weak" },
    { a: "Aaliyah", t: "Are You That Somebody" },
    { a: "Ginuwine", t: "Pony" },
    { a: "Big Pun", t: "Still Not a Player" },
    { a: "Luniz", t: "I Got 5 on It" },
    { a: "Snoop Doggy Dogg", t: "Who Am I (What's My Name)?" },
    { a: "2Pac", t: "How Do U Want It" },
    { a: "Mark Morrison", t: "Return of the Mack" },
    { a: "Shaggy", t: "Boombastic" },
    { a: "Dr. Dre", t: "Still D.R.E." },
    { a: "Jay-Z", t: "Can I Get A..." },
    { a: "Mase", t: "Feel So Good" },
    { a: "Puff Daddy", t: "It's All About the Benjamins" },
    { a: "2Pac", t: "Keep Ya Head Up" },
    { a: "Junior M.A.F.I.A.", t: "Get Money" },
    { a: "Pete Rock and C.L. Smooth", t: "They Reminisce Over You (T.R.O.Y.)" },
    { a: "A Tribe Called Quest", t: "Can I Kick It?" },
    { a: "Bone Thugs-N-Harmony", t: "Tha Crossroads" },
    { a: "Black Sheep", t: "The Choice Is Yours (Revisited)" },
    { a: "Digable Planets", t: "Rebirth of Slick (Cool Like Dat)" },
    { a: "Onyx", t: "Slam" },
    { a: "Ol' Dirty Bastard", t: "Shimmy Shimmy Ya" },
    { a: "Nas", t: "The World Is Yours" },
    { a: "Will Smith", t: "Gettin' Jiggy wit It" },
    { a: "Juvenile", t: "Back That Thang Up" },
    { a: "OutKast", t: "Rosa Parks" },
    { a: "Brandy and Monica", t: "The Boy Is Mine" },
    { a: "Usher", t: "You Make Me Wanna..." },
    { a: "Usher", t: "Nice and Slow" },
    { a: "Next", t: "Too Close" },
    { a: "K-Ci and JoJo", t: "All My Life" },
    { a: "Jodeci", t: "Freek'n You" },
    { a: "Mary J. Blige", t: "Be Happy" },
    { a: "En Vogue", t: "My Lovin' (You're Never Gonna Get It)" },
    { a: "En Vogue", t: "Don't Let Go (Love)" },
    { a: "Toni Braxton", t: "Un-Break My Heart" },
    { a: "Monica", t: "Don't Take It Personal (Just One of Dem Days)" },
    { a: "Zhane", t: "Hey Mr. D.J." },
    { a: "Soul for Real", t: "Candy Rain" },
    { a: "Groove Theory", t: "Tell Me" },
    { a: "Adina Howard", t: "Freak Like Me" },
    { a: "Ghost Town DJs", t: "My Boo" },
    { a: "Boyz II Men", t: "End of the Road" },
    { a: "Mariah Carey", t: "Fantasy" },
    { a: "Mariah Carey", t: "Honey" },
    { a: "Janet Jackson", t: "That's the Way Love Goes" },
    { a: "Whitney Houston", t: "It's Not Right but It's Okay" },
    { a: "Aaliyah", t: "One in a Million" },
    { a: "Aaliyah", t: "Back and Forth" },
    { a: "Keith Sweat", t: "Twisted" },
    { a: "Dru Hill", t: "In My Bed" },
    { a: "Faith Evans", t: "Love Like This" },
    { a: "Xscape", t: "Just Kickin' It" },
    { a: "SWV", t: "Right Here (Human Nature Remix)" },
    { a: "Destiny's Child", t: "Bills, Bills, Bills" },
    { a: "TLC", t: "Creep" },
    { a: "Salt-N-Pepa", t: "Whatta Man" },
    { a: "Queen Latifah", t: "U.N.I.T.Y." },
    { a: "Heavy D and The Boyz", t: "Now That We Found Love" },
    { a: "Positive K", t: "I Got a Man" },
    { a: "Lords of the Underground", t: "Chief Rocka" },
    { a: "Kris Kross", t: "Jump" },
    { a: "Sir Mix-A-Lot", t: "Baby Got Back" },
    { a: "Digital Underground", t: "The Humpty Dance" },
  ] },
  { call: "WQHT", name: "HOT 97 NEW YORK", format: "NY HIP-HOP & R&B", tracks: [
    { a: "The Notorious B.I.G.", t: "Juicy" },
    { a: "Wu-Tang Clan", t: "C.R.E.A.M." },
    { a: "Craig Mack", t: "Flava in Ya Ear" },
    { a: "Mobb Deep", t: "Shook Ones Pt. II" },
    { a: "The Notorious B.I.G.", t: "Big Poppa" },
    { a: "Lord Tariq and Peter Gunz", t: "Deja Vu (Uptown Baby)" },
    { a: "Nas", t: "If I Ruled the World (Imagine That)" },
    { a: "The Notorious B.I.G.", t: "Hypnotize" },
    { a: "Method Man", t: "I'll Be There for You/You're All I Need to Get By" },
    { a: "Puff Daddy and Faith Evans", t: "I'll Be Missing You" },
    { a: "Jay-Z", t: "Hard Knock Life (Ghetto Anthem)" },
    { a: "DMX", t: "Ruff Ryders' Anthem" },
    { a: "Mary J. Blige", t: "Real Love" },
    { a: "A Tribe Called Quest", t: "Scenario" },
    { a: "The Notorious B.I.G.", t: "Mo Money Mo Problems" },
    { a: "Wu-Tang Clan", t: "Protect Ya Neck" },
    { a: "Busta Rhymes", t: "Woo-Hah!! Got You All in Check" },
    { a: "Naughty by Nature", t: "O.P.P." },
    { a: "Fugees", t: "Killing Me Softly" },
    { a: "LL Cool J", t: "Mama Said Knock You Out" },
    { a: "Puff Daddy", t: "It's All About the Benjamins" },
    { a: "Junior M.A.F.I.A.", t: "Player's Anthem" },
    { a: "Nas", t: "It Ain't Hard to Tell" },
    { a: "Big Pun", t: "Still Not a Player" },
    { a: "Method Man", t: "Bring the Pain" },
    { a: "Puff Daddy", t: "Can't Nobody Hold Me Down" },
    { a: "Mase", t: "Feel So Good" },
    { a: "Jay-Z", t: "Can I Get A..." },
    { a: "Busta Rhymes", t: "Put Your Hands Where My Eyes Could See" },
    { a: "A Tribe Called Quest", t: "Award Tour" },
    { a: "Pete Rock and CL Smooth", t: "They Reminisce Over You (T.R.O.Y.)" },
    { a: "Naughty by Nature", t: "Hip Hop Hooray" },
    { a: "SWV", t: "Weak" },
    { a: "TLC", t: "Creep" },
    { a: "Mary J. Blige", t: "You Remind Me" },
    { a: "Junior M.A.F.I.A.", t: "Get Money" },
    { a: "Lil' Kim", t: "Crush on You" },
    { a: "Missy Elliott", t: "The Rain (Supa Dupa Fly)" },
    { a: "DMX", t: "Get at Me Dog" },
    { a: "The Lox", t: "Money, Power & Respect" },
    { a: "Jay-Z", t: "Ain't No Nigga" },
    { a: "Ol' Dirty Bastard", t: "Shimmy Shimmy Ya" },
    { a: "Mobb Deep", t: "Quiet Storm" },
    { a: "KRS-One", t: "Step into a World (Rapture's Delight)" },
    { a: "Onyx", t: "Slam" },
    { a: "Gang Starr", t: "DWYCK" },
    { a: "Black Sheep", t: "The Choice Is Yours (Revisited)" },
    { a: "Das EFX", t: "They Want EFX" },
    { a: "Queen Latifah", t: "U.N.I.T.Y." },
    { a: "Aaliyah", t: "Back & Forth" },
    { a: "Aaliyah", t: "One in a Million" },
    { a: "Aaliyah", t: "Are You That Somebody" },
    { a: "Ginuwine", t: "Pony" },
    { a: "Usher", t: "You Make Me Wanna..." },
    { a: "Blackstreet", t: "No Diggity" },
    { a: "Mariah Carey", t: "Fantasy (Bad Boy Remix)" },
    { a: "Mariah Carey", t: "Heartbreaker" },
    { a: "Total", t: "Can't You See" },
    { a: "Faith Evans", t: "You Used to Love Me" },
    { a: "112", t: "Only You" },
    { a: "Jodeci", t: "Freek'n You" },
    { a: "Soul for Real", t: "Candy Rain" },
    { a: "Montell Jordan", t: "This Is How We Do It" },
    { a: "Mary J. Blige", t: "I'm Goin' Down" },
    { a: "TLC", t: "Waterfalls" },
    { a: "TLC", t: "No Scrubs" },
    { a: "SWV", t: "Right Here (Human Nature Remix)" },
    { a: "Lauryn Hill", t: "Doo Wop (That Thing)" },
    { a: "Fugees", t: "Ready or Not" },
    { a: "Wyclef Jean", t: "Gone till November" },
    { a: "Pras", t: "Ghetto Supastar (That Is What You Are)" },
    { a: "LL Cool J", t: "Loungin" },
    { a: "LL Cool J", t: "Around the Way Girl" },
    { a: "Lost Boyz", t: "Renee" },
    { a: "AZ", t: "Sugar Hill" },
    { a: "Fat Joe", t: "Flow Joe" },
    { a: "Cam'ron", t: "Horse & Carriage" },
    { a: "Noreaga", t: "Superthug" },
    { a: "Missy Elliott", t: "Hot Boyz" },
    { a: "Foxy Brown", t: "I'll Be" },
    { a: "Dr. Dre", t: "Nuthin' but a 'G' Thang" },
    { a: "Snoop Doggy Dogg", t: "Gin and Juice" },
    { a: "2Pac", t: "California Love" },
    { a: "2Pac", t: "Dear Mama" },
    { a: "Warren G", t: "Regulate" },
    { a: "Coolio", t: "Gangsta's Paradise" },
    { a: "Luniz", t: "I Got 5 on It" },
    { a: "Bone Thugs-n-Harmony", t: "Tha Crossroads" },
    { a: "Digital Underground", t: "The Humpty Dance" },
    { a: "Heavy D and the Boyz", t: "Now That We Found Love" },
    { a: "Bell Biv DeVoe", t: "Poison" },
    { a: "Ini Kamoze", t: "Here Comes the Hotstepper" },
    { a: "Chaka Demus and Pliers", t: "Murder She Wrote" },
    { a: "Shabba Ranks", t: "Mr. Loverman" },
    { a: "C+C Music Factory", t: "Gonna Make You Sweat (Everybody Dance Now)" },
    { a: "Black Box", t: "Everybody Everybody" },
    { a: "Deee-Lite", t: "Groove Is in the Heart" },
    { a: "Crystal Waters", t: "Gypsy Woman (She's Homeless)" },
    { a: "CeCe Peniston", t: "Finally" },
    { a: "Lisette Melendez", t: "Together Forever" },
  ] },
  { call: "KACD", name: "GROOVE RADIO 103.1 LOS ANGELES", format: "ELECTRONICA / DANCE", tracks: [
    { a: "The Prodigy", t: "Firestarter" },
    { a: "The Chemical Brothers", t: "Block Rockin' Beats" },
    { a: "Underworld", t: "Born Slippy (Nuxx)" },
    { a: "Daft Punk", t: "Around the World" },
    { a: "Fatboy Slim", t: "The Rockafeller Skank" },
    { a: "The Prodigy", t: "Breathe" },
    { a: "Orbital", t: "Halcyon and On and On" },
    { a: "Moby", t: "Go" },
    { a: "The Crystal Method", t: "Busy Child" },
    { a: "Leftfield", t: "Open Up" },
    { a: "Robert Miles", t: "Children" },
    { a: "Massive Attack", t: "Unfinished Sympathy" },
    { a: "Josh Wink", t: "Higher State of Consciousness" },
    { a: "The Chemical Brothers", t: "Setting Sun" },
    { a: "Daft Punk", t: "Da Funk" },
    { a: "Goldie", t: "Inner City Life" },
    { a: "Faithless", t: "Insomnia" },
    { a: "The Orb", t: "Little Fluffy Clouds" },
    { a: "BT", t: "Flaming June" },
    { a: "Paul van Dyk", t: "For an Angel" },
    { a: "Fatboy Slim", t: "Praise You" },
    { a: "The KLF", t: "3 A.M. Eternal" },
    { a: "Aphex Twin", t: "Windowlicker" },
    { a: "Roni Size / Reprazent", t: "Brown Paper Bag" },
    { a: "Bjork", t: "Big Time Sensuality" },
    { a: "The Prodigy", t: "Smack My Bitch Up" },
    { a: "Underworld", t: "Rez" },
    { a: "Energy 52", t: "Cafe del Mar" },
    { a: "The Chemical Brothers", t: "Hey Boy Hey Girl" },
    { a: "Stardust", t: "Music Sounds Better with You" },
    { a: "Moby", t: "Porcelain" },
    { a: "Portishead", t: "Glory Box" },
    { a: "Orbital", t: "Chime" },
    { a: "Propellerheads", t: "History Repeating" },
    { a: "Deee-Lite", t: "Groove Is in the Heart" },
    { a: "Armand Van Helden", t: "The Funk Phenomena" },
    { a: "The KLF", t: "What Time Is Love?" },
    { a: "Fatboy Slim", t: "Right Here, Right Now" },
    { a: "The Future Sound of London", t: "Papua New Guinea" },
    { a: "The Prodigy", t: "Out of Space" },
    { a: "Massive Attack", t: "Teardrop" },
    { a: "Tricky", t: "Hell Is Round the Corner" },
    { a: "The Shamen", t: "Move Any Mountain" },
    { a: "Joey Beltram", t: "Energy Flash" },
    { a: "LFO", t: "LFO" },
    { a: "Underworld", t: "Cowgirl" },
    { a: "Crystal Waters", t: "Gypsy Woman (She's Homeless)" },
    { a: "Sasha", t: "Xpander" },
    { a: "The Crystal Method", t: "Trip Like I Do" },
    { a: "Leftfield", t: "Release the Pressure" },
    { a: "Delerium feat. Sarah McLachlan", t: "Silence" },
    { a: "ATB", t: "9 PM (Till I Come)" },
    { a: "Grace", t: "Not Over Yet" },
    { a: "Everything but the Girl", t: "Missing (Todd Terry Remix)" },
    { a: "Ultra Nate", t: "Free" },
    { a: "Daft Punk", t: "Revolution 909" },
    { a: "LTJ Bukem", t: "Horizons" },
    { a: "Adam F", t: "Circles" },
    { a: "Roni Size / Reprazent", t: "Heroes" },
    { a: "Aphex Twin", t: "Come to Daddy" },
    { a: "The Orb", t: "Blue Room" },
    { a: "Bjork", t: "Hyperballad" },
    { a: "Bjork", t: "Army of Me" },
    { a: "Moby", t: "Bodyrock" },
    { a: "Moby", t: "Honey" },
    { a: "The Chemical Brothers", t: "Leave Home" },
    { a: "The Crystal Method", t: "Keep Hope Alive" },
    { a: "Winx", t: "Don't Laugh" },
    { a: "Green Velvet", t: "Flash" },
    { a: "CJ Bolland", t: "Sugar Is Sweeter" },
    { a: "Hardfloor", t: "Acperience 1" },
    { a: "Age of Love", t: "The Age of Love" },
    { a: "Jam & Spoon feat. Plavka", t: "Right in the Night" },
    { a: "Three Drives", t: "Greece 2000" },
    { a: "System F", t: "Out of the Blue" },
    { a: "Chicane", t: "Saltwater" },
    { a: "Binary Finary", t: "1998" },
    { a: "Faithless", t: "God Is a DJ" },
    { a: "Basement Jaxx", t: "Red Alert" },
    { a: "Cassius", t: "Cassius 1999" },
    { a: "Mr. Oizo", t: "Flat Beat" },
    { a: "Armand Van Helden feat. Duane Harden", t: "U Don't Know Me" },
    { a: "The Bucketheads", t: "The Bomb! (These Sounds Fall into My Mind)" },
    { a: "Moloko", t: "Sing It Back" },
    { a: "808 State", t: "Cubik" },
    { a: "Utah Saints", t: "Something Good" },
    { a: "SL2", t: "On a Ragga Tip" },
    { a: "Bizarre Inc", t: "Playing with Knives" },
    { a: "Altern-8", t: "Activ-8 (Come with Me)" },
    { a: "DJ Shadow", t: "Midnight in a Perfect World" },
    { a: "Sneaker Pimps", t: "6 Underground" },
    { a: "Air", t: "Sexy Boy" },
    { a: "Portishead", t: "Sour Times" },
    { a: "Tricky", t: "Black Steel" },
    { a: "Massive Attack", t: "Safe from Harm" },
    { a: "Underworld", t: "Push Upstairs" },
    { a: "Leftfield", t: "Phat Planet" },
    { a: "Lo Fidelity Allstars feat. Pigeonhed", t: "Battleflag" },
    { a: "The Orb", t: "Toxygene" },
    { a: "BT", t: "Remember" },
  ] },
  { call: "WZBC", name: "WZBC 90.3 BOSTON COLLEGE RADIO", format: "COLLEGE INDIE / EXPERIMENTAL", tracks: [
    { a: "Pixies", t: "Velouria" },
    { a: "Sleater-Kinney", t: "Dig Me Out" },
    { a: "My Bloody Valentine", t: "Only Shallow" },
    { a: "Sonic Youth", t: "Kool Thing" },
    { a: "Pavement", t: "Cut Your Hair" },
    { a: "Versus", t: "Deep Red" },
    { a: "Galaxie 500", t: "Fourth of July" },
    { a: "Morphine", t: "Cure for Pain" },
    { a: "Stereolab", t: "French Disko" },
    { a: "Guided by Voices", t: "I Am a Scientist" },
    { a: "Sebadoh", t: "Soul and Fire" },
    { a: "Team Dresch", t: "She's Amazing" },
    { a: "Yo La Tengo", t: "Autumn Sweater" },
    { a: "Massive Attack", t: "Teardrop" },
    { a: "Air", t: "All I Need" },
    { a: "Slowdive", t: "When the Sun Hits" },
    { a: "The Amps", t: "Tipp City" },
    { a: "Superchunk", t: "Slack Motherfucker" },
    { a: "Dinosaur Jr", t: "The Wagon" },
    { a: "Throwing Muses", t: "Counting Backwards" },
    { a: "Belly", t: "Feed the Tree" },
    { a: "Buffalo Tom", t: "Taillights Fade" },
    { a: "The Lemonheads", t: "It's a Shame About Ray" },
    { a: "Portishead", t: "Sour Times" },
    { a: "Bjork", t: "Hyperballad" },
    { a: "PJ Harvey", t: "Sheela-Na-Gig" },
    { a: "Pixies", t: "Planet of Sound" },
    { a: "Ride", t: "Vapour Trail" },
    { a: "Lush", t: "Sweetness and Light" },
    { a: "Cocteau Twins", t: "Cherry-Coloured Funk" },
    { a: "His Name Is Alive", t: "The Dirt Eaters" },
    { a: "Come", t: "Fast Piss Blues" },
    { a: "Swirlies", t: "Bell" },
    { a: "Helium", t: "Superball" },
    { a: "Juliana Hatfield", t: "My Sister" },
    { a: "Pavement", t: "Gold Soundz" },
    { a: "Sonic Youth", t: "Bull in the Heather" },
    { a: "Mudhoney", t: "Suck You Dry" },
    { a: "The Sea and Cake", t: "Parasol" },
    { a: "Palace Brothers", t: "Ohio River Boat Song" },
    { a: "Neutral Milk Hotel", t: "Holland, 1945" },
    { a: "Elliott Smith", t: "Between the Bars" },
    { a: "Built to Spill", t: "Carry the Zero" },
    { a: "Modest Mouse", t: "Dramamine" },
    { a: "Cat Power", t: "Nude as the News" },
    { a: "Liz Phair", t: "Never Said" },
    { a: "Bikini Kill", t: "Rebel Girl" },
    { a: "Sleater-Kinney", t: "Call the Doctor" },
    { a: "Fugazi", t: "Merchandise" },
    { a: "Unwound", t: "Corpse Pose" },
    { a: "Archers of Loaf", t: "Web in Front" },
    { a: "Polvo", t: "Vibracobra" },
    { a: "Chavez", t: "Break Up Your Band" },
    { a: "Jawbox", t: "Savory" },
    { a: "Guided by Voices", t: "Game of Pricks" },
    { a: "Slint", t: "Good Morning, Captain" },
    { a: "Codeine", t: "D" },
    { a: "Low", t: "Over the Ocean" },
    { a: "They Might Be Giants", t: "Birdhouse in Your Soul" },
    { a: "Red House Painters", t: "Katy Song" },
    { a: "Tortoise", t: "Djed" },
    { a: "Mogwai", t: "Mogwai Fear Satan" },
    { a: "Godspeed You Black Emperor", t: "East Hastings" },
    { a: "Labradford", t: "Accelerating on a Smoother Road" },
    { a: "Flying Saucer Attack", t: "Land Beyond the Sun" },
    { a: "Bowery Electric", t: "Beat" },
    { a: "Seefeel", t: "Time to Find Me" },
    { a: "Aphex Twin", t: "Xtal" },
    { a: "Boards of Canada", t: "Roygbiv" },
    { a: "The Orb", t: "Little Fluffy Clouds" },
    { a: "DJ Shadow", t: "Midnight in a Perfect World" },
    { a: "Sugar", t: "If I Can't Change Your Mind" },
    { a: "Massive Attack", t: "Unfinished Sympathy" },
    { a: "Stereolab", t: "Metronomic Underground" },
    { a: "Broadcast", t: "The Book Lovers" },
    { a: "Spiritualized", t: "Ladies and Gentlemen We Are Floating in Space" },
    { a: "Spacemen 3", t: "Big City" },
    { a: "Loop", t: "Arc-Lite" },
    { a: "Catherine Wheel", t: "Black Metallic" },
    { a: "Chapterhouse", t: "Pearl" },
    { a: "Beta Band", t: "Dry the Rain" },
    { a: "Velocity Girl", t: "My Forgotten Favorite" },
    { a: "Belle and Sebastian", t: "The State I Am In" },
    { a: "Bardo Pond", t: "Tommy Gun Angel" },
    { a: "The Wedding Present", t: "Brassneck" },
    { a: "The Magnetic Fields", t: "Strange Powers" },
    { a: "The Sundays", t: "Here's Where the Story Ends" },
    { a: "Teenage Fanclub", t: "The Concept" },
    { a: "The Charlatans", t: "The Only One I Know" },
    { a: "Sebadoh", t: "Rebound" },
    { a: "Luna", t: "23 Minutes in Brussels" },
    { a: "The Boo Radleys", t: "Lazarus" },
    { a: "Bel Canto", t: "Intravenous" },
    { a: "Stina Nordenstam", t: "Little Star" },
    { a: "Kent", t: "If You Were Here" },
    { a: "Mercury Rev", t: "Goddess on a Hiway" },
    { a: "The Flaming Lips", t: "Race for the Prize" },
    { a: "The Dambuilders", t: "Shrine" },
    { a: "Silver Jews", t: "Random Rules" },
    { a: "Smog", t: "Cold Blooded Old Times" },
  ] },
  { call: "KROQ", name: "KROQ 106.7 LOS ANGELES", format: "ALTERNATIVE", tracks: [
    { a: "Nirvana", t: "Smells Like Teen Spirit" },
    { a: "Sublime", t: "Date Rape" },
    { a: "The Offspring", t: "Self Esteem" },
    { a: "blink-182", t: "Dammit" },
    { a: "Beastie Boys", t: "Intergalactic" },
    { a: "Stone Temple Pilots", t: "Plush" },
    { a: "Radiohead", t: "Creep" },
    { a: "Sublime", t: "What I Got" },
    { a: "Beck", t: "Loser" },
    { a: "Rage Against the Machine", t: "Killing in the Name" },
    { a: "Nirvana", t: "Come As You Are" },
    { a: "Red Hot Chili Peppers", t: "Under the Bridge" },
    { a: "Limp Bizkit", t: "Nookie" },
    { a: "No Doubt", t: "Just a Girl" },
    { a: "The Offspring", t: "Come Out and Play" },
    { a: "Pearl Jam", t: "Alive" },
    { a: "blink-182", t: "What's My Age Again?" },
    { a: "Sublime", t: "Wrong Way" },
    { a: "Korn", t: "Freak on a Leash" },
    { a: "Green Day", t: "When I Come Around" },
    { a: "311", t: "Down" },
    { a: "Foo Fighters", t: "Everlong" },
    { a: "Sublime", t: "Santeria" },
    { a: "Sinead O'Connor", t: "Nothing Compares 2 U" },
    { a: "Red Hot Chili Peppers", t: "Scar Tissue" },
    { a: "Blur", t: "Song 2" },
    { a: "The Smashing Pumpkins", t: "Today" },
    { a: "Nine Inch Nails", t: "Closer" },
    { a: "Metallica", t: "Enter Sandman" },
    { a: "The Smashing Pumpkins", t: "1979" },
    { a: "Korn", t: "Got the Life" },
    { a: "Nirvana", t: "Lithium" },
    { a: "The Offspring", t: "Pretty Fly (for a White Guy)" },
    { a: "Pearl Jam", t: "Jeremy" },
    { a: "No Doubt", t: "Spiderwebs" },
    { a: "Jesus Jones", t: "Right Here, Right Now" },
    { a: "blink-182", t: "Josie" },
    { a: "Sugar Ray", t: "Fly" },
    { a: "Green Day", t: "Good Riddance (Time of Your Life)" },
    { a: "Jane's Addiction", t: "Been Caught Stealing" },
    { a: "Beck", t: "Where It's At" },
    { a: "Nine Inch Nails", t: "Head Like a Hole" },
    { a: "Beastie Boys", t: "Sabotage" },
    { a: "Depeche Mode", t: "Enjoy the Silence" },
    { a: "EMF", t: "Unbelievable" },
    { a: "Green Day", t: "Longview" },
    { a: "Live", t: "Lightning Crashes" },
    { a: "Hole", t: "Celebrity Skin" },
    { a: "Cake", t: "The Distance" },
    { a: "Harvey Danger", t: "Flagpole Sitta" },
    { a: "Rage Against the Machine", t: "Bulls on Parade" },
    { a: "No Doubt", t: "Don't Speak" },
    { a: "Pearl Jam", t: "Even Flow" },
    { a: "Nine Inch Nails", t: "Hurt" },
    { a: "The Cure", t: "Pictures of You" },
    { a: "The Cure", t: "A Letter to Elise" },
    { a: "Smash Mouth", t: "Walkin' on the Sun" },
    { a: "Metallica", t: "The Unforgiven" },
    { a: "311", t: "All Mixed Up" },
    { a: "The Smashing Pumpkins", t: "Disarm" },
    { a: "Kid Rock", t: "Bawitdaba" },
    { a: "Goo Goo Dolls", t: "Iris" },
    { a: "Blind Melon", t: "No Rain" },
    { a: "The Smashing Pumpkins", t: "Bullet with Butterfly Wings" },
    { a: "Lit", t: "My Own Worst Enemy" },
    { a: "U2", t: "One" },
    { a: "U2", t: "Mysterious Ways" },
    { a: "Third Eye Blind", t: "Semi-Charmed Life" },
    { a: "Alice in Chains", t: "Man in the Box" },
    { a: "Gin Blossoms", t: "Hey Jealousy" },
    { a: "The Cranberries", t: "Linger" },
    { a: "Pearl Jam", t: "Last Kiss" },
    { a: "Marcy Playground", t: "Sex and Candy" },
    { a: "Red Hot Chili Peppers", t: "Give It Away" },
    { a: "Tori Amos", t: "Silent All These Years" },
    { a: "Beastie Boys", t: "Sure Shot" },
    { a: "Green Day", t: "Basket Case" },
    { a: "Stone Temple Pilots", t: "Vasoline" },
    { a: "Garbage", t: "#1 Crush" },
    { a: "Bush", t: "Comedown" },
    { a: "Cake", t: "Never There" },
    { a: "Jane's Addiction", t: "Jane Says" },
    { a: "Faith No More", t: "Epic" },
    { a: "Metallica", t: "Nothing Else Matters" },
    { a: "The Presidents of the United States of America", t: "Lump" },
    { a: "Sugar Ray", t: "Every Morning" },
    { a: "Fatboy Slim", t: "The Rockafeller Skank" },
    { a: "Everlast", t: "What It's Like" },
    { a: "White Zombie", t: "More Human Than Human" },
    { a: "The Offspring", t: "The Kids Aren't Alright" },
    { a: "Weezer", t: "Buddy Holly" },
    { a: "Alanis Morissette", t: "You Oughta Know" },
    { a: "Limp Bizkit", t: "Faith" },
    { a: "Fatboy Slim", t: "Praise You" },
    { a: "Korn", t: "Blind" },
    { a: "Nirvana", t: "About a Girl" },
    { a: "Oasis", t: "Wonderwall" },
    { a: "R.E.M.", t: "Losing My Religion" },
    { a: "Kid Rock", t: "Cowboy" },
    { a: "Tool", t: "Sober" },
  ] },
  { call: "WAAF", name: "107.3 WAAF BOSTON", format: "ACTIVE ROCK", tracks: [
    { a: "Godsmack", t: "Whatever" },
    { a: "Alice in Chains", t: "Man in the Box" },
    { a: "Metallica", t: "Enter Sandman" },
    { a: "Nirvana", t: "Smells Like Teen Spirit" },
    { a: "Pearl Jam", t: "Alive" },
    { a: "Rage Against the Machine", t: "Killing in the Name" },
    { a: "Soundgarden", t: "Black Hole Sun" },
    { a: "Stone Temple Pilots", t: "Plush" },
    { a: "Tool", t: "Sober" },
    { a: "White Zombie", t: "Thunder Kiss '65" },
    { a: "Pearl Jam", t: "Even Flow" },
    { a: "Alice in Chains", t: "Would?" },
    { a: "Metallica", t: "Sad But True" },
    { a: "Korn", t: "Freak on a Leash" },
    { a: "Godsmack", t: "Keep Away" },
    { a: "Bush", t: "Machinehead" },
    { a: "Rob Zombie", t: "Dragula" },
    { a: "Soundgarden", t: "Outshined" },
    { a: "Stone Temple Pilots", t: "Interstate Love Song" },
    { a: "Aerosmith", t: "Livin' on the Edge" },
    { a: "Nirvana", t: "Come as You Are" },
    { a: "Ozzy Osbourne", t: "No More Tears" },
    { a: "Rage Against the Machine", t: "Bulls on Parade" },
    { a: "Foo Fighters", t: "Everlong" },
    { a: "Alice in Chains", t: "Rooster" },
    { a: "Guns N' Roses", t: "You Could Be Mine" },
    { a: "Marilyn Manson", t: "The Beautiful People" },
    { a: "Metallica", t: "The Unforgiven" },
    { a: "Pearl Jam", t: "Jeremy" },
    { a: "Tool", t: "Aenema" },
    { a: "Creed", t: "My Own Prison" },
    { a: "Limp Bizkit", t: "Nookie" },
    { a: "The Offspring", t: "Come Out and Play" },
    { a: "Filter", t: "Hey Man Nice Shot" },
    { a: "Danzig", t: "Mother" },
    { a: "Pantera", t: "Walk" },
    { a: "White Zombie", t: "More Human Than Human" },
    { a: "The Smashing Pumpkins", t: "Bullet with Butterfly Wings" },
    { a: "Nine Inch Nails", t: "Closer" },
    { a: "Live", t: "Lightning Crashes" },
    { a: "Stone Temple Pilots", t: "Vasoline" },
    { a: "Soundgarden", t: "Spoonman" },
    { a: "Candlebox", t: "Far Behind" },
    { a: "Faith No More", t: "Epic" },
    { a: "Aerosmith", t: "Cryin'" },
    { a: "Extreme", t: "Get the Funk Out" },
    { a: "Kid Rock", t: "Bawitdaba" },
    { a: "Staind", t: "Mudshovel" },
    { a: "Powerman 5000", t: "When Worlds Collide" },
    { a: "Metallica", t: "Fuel" },
    { a: "Nirvana", t: "Lithium" },
    { a: "Van Halen", t: "Right Now" },
    { a: "Queensryche", t: "Silent Lucidity" },
    { a: "Megadeth", t: "Symphony of Destruction" },
    { a: "AC/DC", t: "Thunderstruck" },
    { a: "Temple of the Dog", t: "Hunger Strike" },
    { a: "Alice in Chains", t: "No Excuses" },
    { a: "Green Day", t: "Basket Case" },
    { a: "Foo Fighters", t: "Monkey Wrench" },
    { a: "Bush", t: "Comedown" },
    { a: "Collective Soul", t: "Shine" },
    { a: "Days of the New", t: "Touch, Peel and Stand" },
    { a: "Fuel", t: "Shimmer" },
    { a: "Monster Magnet", t: "Space Lord" },
    { a: "Marilyn Manson", t: "The Dope Show" },
    { a: "Korn", t: "Got the Life" },
    { a: "Deftones", t: "My Own Summer (Shove It)" },
    { a: "Creed", t: "Higher" },
    { a: "The Offspring", t: "Self Esteem" },
    { a: "Red Hot Chili Peppers", t: "Give It Away" },
    { a: "Red Hot Chili Peppers", t: "Under the Bridge" },
    { a: "Jane's Addiction", t: "Been Caught Stealing" },
    { a: "The Black Crowes", t: "Hard to Handle" },
    { a: "Guns N' Roses", t: "November Rain" },
    { a: "Nine Inch Nails", t: "Head Like a Hole" },
    { a: "Beastie Boys", t: "Sabotage" },
    { a: "Toadies", t: "Possum Kingdom" },
    { a: "Sponge", t: "Plowed" },
    { a: "Seven Mary Three", t: "Cumbersome" },
    { a: "Local H", t: "Bound for the Floor" },
    { a: "Stabbing Westward", t: "Save Yourself" },
    { a: "Rammstein", t: "Du Hast" },
    { a: "Silverchair", t: "Tomorrow" },
    { a: "Everclear", t: "Santa Monica" },
    { a: "Nirvana", t: "Heart-Shaped Box" },
    { a: "Pantera", t: "I'm Broken" },
    { a: "Screaming Trees", t: "Nearly Lost You" },
    { a: "Helmet", t: "Unsung" },
    { a: "Primus", t: "Jerry Was a Race Car Driver" },
    { a: "Ugly Kid Joe", t: "Everything About You" },
    { a: "Type O Negative", t: "Black No. 1" },
    { a: "Pearl Jam", t: "Black" },
    { a: "Skid Row", t: "Monkey Business" },
    { a: "311", t: "Down" },
    { a: "Lit", t: "My Own Worst Enemy" },
    { a: "Buckcherry", t: "Lit Up" },
    { a: "Limp Bizkit", t: "Faith" },
    { a: "Bad Religion", t: "21st Century (Digital Boy)" },
    { a: "Extreme", t: "Hole Hearted" },
    { a: "Godsmack", t: "Voodoo" },
  ] },
  { call: "WLTW", name: "106.7 LITE FM NEW YORK", format: "RELAXING FAVORITES", tracks: [
    { a: "Whitney Houston", t: "I Will Always Love You" },
    { a: "Celine Dion", t: "Because You Loved Me" },
    { a: "Bryan Adams", t: "(Everything I Do) I Do It for You" },
    { a: "Mariah Carey", t: "Hero" },
    { a: "Celine Dion", t: "My Heart Will Go On" },
    { a: "Eric Clapton", t: "Tears in Heaven" },
    { a: "Elton John", t: "Can You Feel the Love Tonight" },
    { a: "Toni Braxton", t: "Un-Break My Heart" },
    { a: "Boyz II Men", t: "End of the Road" },
    { a: "Michael Bolton", t: "How Am I Supposed to Live Without You" },
    { a: "Phil Collins", t: "Another Day in Paradise" },
    { a: "Mariah Carey and Boyz II Men", t: "One Sweet Day" },
    { a: "Savage Garden", t: "Truly Madly Deeply" },
    { a: "Celine Dion", t: "The Power of Love" },
    { a: "Whitney Houston", t: "Exhale (Shoop Shoop)" },
    { a: "Elton John", t: "Candle in the Wind 1997" },
    { a: "Boyz II Men", t: "I'll Make Love to You" },
    { a: "All-4-One", t: "I Swear" },
    { a: "Rod Stewart", t: "Have I Told You Lately" },
    { a: "Michael Bolton", t: "When a Man Loves a Woman" },
    { a: "Bette Midler", t: "From a Distance" },
    { a: "Extreme", t: "More Than Words" },
    { a: "Amy Grant", t: "Baby Baby" },
    { a: "Vanessa Williams", t: "Save the Best for Last" },
    { a: "Wilson Phillips", t: "Hold On" },
    { a: "Mariah Carey", t: "Vision of Love" },
    { a: "Bryan Adams", t: "Please Forgive Me" },
    { a: "Shania Twain", t: "You're Still the One" },
    { a: "Roxette", t: "It Must Have Been Love" },
    { a: "LeAnn Rimes", t: "How Do I Live" },
    { a: "R. Kelly", t: "I Believe I Can Fly" },
    { a: "Seal", t: "Kiss from a Rose" },
    { a: "Toni Braxton", t: "Breathe Again" },
    { a: "Gloria Estefan", t: "Coming Out of the Dark" },
    { a: "Richard Marx", t: "Now and Forever" },
    { a: "Aerosmith", t: "I Don't Want to Miss a Thing" },
    { a: "Whitney Houston", t: "I Have Nothing" },
    { a: "Luther Vandross", t: "Here and Now" },
    { a: "Taylor Dayne", t: "Love Will Lead You Back" },
    { a: "Celine Dion", t: "It's All Coming Back to Me Now" },
    { a: "Peabo Bryson and Regina Belle", t: "A Whole New World" },
    { a: "Eric Clapton", t: "Change the World" },
    { a: "Goo Goo Dolls", t: "Iris" },
    { a: "Sarah McLachlan", t: "Angel" },
    { a: "Jewel", t: "Foolish Games" },
    { a: "Faith Hill", t: "This Kiss" },
    { a: "Savage Garden", t: "I Knew I Loved You" },
    { a: "Elton John", t: "The One" },
    { a: "Phil Collins", t: "I Wish It Would Rain Down" },
    { a: "Bonnie Raitt", t: "I Can't Make You Love Me" },
    { a: "Marc Cohn", t: "Walking in Memphis" },
    { a: "Jon Secada", t: "Just Another Day" },
    { a: "Madonna", t: "Take a Bow" },
    { a: "Janet Jackson", t: "Again" },
    { a: "Boyz II Men", t: "Water Runs Dry" },
    { a: "Bryan Adams", t: "Have You Ever Really Loved a Woman?" },
    { a: "Rod Stewart", t: "Rhythm of My Heart" },
    { a: "Michael Bolton", t: "Said I Loved You...But I Lied" },
    { a: "Richard Marx", t: "Hazard" },
    { a: "Gloria Estefan", t: "Here We Are" },
    { a: "Amy Grant", t: "Every Heartbeat" },
    { a: "Mariah Carey", t: "Can't Let Go" },
    { a: "Whitney Houston", t: "All the Man That I Need" },
    { a: "Kenny G", t: "Forever in Love" },
    { a: "Kenny G with Peabo Bryson", t: "By the Time This Night Is Over" },
    { a: "Oleta Adams", t: "Get Here" },
    { a: "Surface", t: "The First Time" },
    { a: "Expose", t: "I'll Never Get Over You (Getting Over Me)" },
    { a: "All-4-One", t: "I Can Love You Like That" },
    { a: "Shania Twain", t: "From This Moment On" },
    { a: "Faith Hill", t: "Breathe" },
    { a: "Donna Lewis", t: "I Love You Always Forever" },
    { a: "Duncan Sheik", t: "Barely Breathing" },
    { a: "Natalie Imbruglia", t: "Torn" },
    { a: "Sixpence None the Richer", t: "Kiss Me" },
    { a: "Edwin McCain", t: "I'll Be" },
    { a: "Shawn Colvin", t: "Sunny Came Home" },
    { a: "Paula Cole", t: "I Don't Want to Wait" },
    { a: "Lisa Loeb", t: "Stay (I Missed You)" },
    { a: "Sarah McLachlan", t: "I Will Remember You" },
    { a: "Sarah McLachlan", t: "Adia" },
    { a: "Jewel", t: "You Were Meant for Me" },
    { a: "Jewel", t: "Hands" },
    { a: "Natalie Merchant", t: "Wonder" },
    { a: "Natalie Merchant", t: "Carnival" },
    { a: "Sting", t: "Fields of Gold" },
    { a: "Bonnie Raitt", t: "Something to Talk About" },
    { a: "Vanessa Williams", t: "Colors of the Wind" },
    { a: "Vanessa Williams and Brian McKnight", t: "Love Is" },
    { a: "Wilson Phillips", t: "You're in Love" },
    { a: "Phil Collins", t: "You'll Be in My Heart" },
    { a: "Phil Collins", t: "Do You Remember" },
    { a: "Elton John", t: "Something About the Way You Look Tonight" },
    { a: "Rod Stewart", t: "Downtown Train" },
    { a: "Richard Marx", t: "Keep Coming Back" },
    { a: "Michael Bolton", t: "Time, Love and Tenderness" },
    { a: "Toni Braxton", t: "You Mean the World to Me" },
    { a: "Amy Grant", t: "That's What Love Is For" },
    { a: "Bryan Adams and Barbra Streisand", t: "I Finally Found Someone" },
    { a: "Gloria Estefan and NSYNC", t: "Music of My Heart" },
  ] },
  { call: "KITS", name: "LIVE 105 SAN FRANCISCO", format: "MODERN ROCK", tracks: [
    { a: "Nirvana", t: "Smells Like Teen Spirit" },
    { a: "Pearl Jam", t: "Alive" },
    { a: "Green Day", t: "Basket Case" },
    { a: "Red Hot Chili Peppers", t: "Under the Bridge" },
    { a: "Smashing Pumpkins", t: "1979" },
    { a: "Radiohead", t: "Creep" },
    { a: "Beck", t: "Loser" },
    { a: "Oasis", t: "Wonderwall" },
    { a: "Third Eye Blind", t: "Semi-Charmed Life" },
    { a: "Depeche Mode", t: "Enjoy the Silence" },
    { a: "Soundgarden", t: "Black Hole Sun" },
    { a: "Alice in Chains", t: "Man in the Box" },
    { a: "Stone Temple Pilots", t: "Plush" },
    { a: "Nirvana", t: "Come as You Are" },
    { a: "Weezer", t: "Buddy Holly" },
    { a: "Beastie Boys", t: "Sabotage" },
    { a: "Green Day", t: "Longview" },
    { a: "Sublime", t: "What I Got" },
    { a: "Foo Fighters", t: "Everlong" },
    { a: "The Cure", t: "Friday I'm in Love" },
    { a: "Red Hot Chili Peppers", t: "Give It Away" },
    { a: "Counting Crows", t: "Mr. Jones" },
    { a: "Nine Inch Nails", t: "Closer" },
    { a: "U2", t: "One" },
    { a: "R.E.M.", t: "Losing My Religion" },
    { a: "Jane's Addiction", t: "Been Caught Stealing" },
    { a: "Bush", t: "Glycerine" },
    { a: "The Offspring", t: "Come Out and Play" },
    { a: "No Doubt", t: "Just a Girl" },
    { a: "Faith No More", t: "Epic" },
    { a: "Pearl Jam", t: "Jeremy" },
    { a: "Smashing Pumpkins", t: "Bullet with Butterfly Wings" },
    { a: "Chris Isaak", t: "Wicked Game" },
    { a: "Stone Temple Pilots", t: "Interstate Love Song" },
    { a: "Green Day", t: "When I Come Around" },
    { a: "Nirvana", t: "Lithium" },
    { a: "Blur", t: "Song 2" },
    { a: "The Verve", t: "Bitter Sweet Symphony" },
    { a: "Rage Against the Machine", t: "Killing in the Name" },
    { a: "Live", t: "Lightning Crashes" },
    { a: "Alanis Morissette", t: "You Oughta Know" },
    { a: "The Cranberries", t: "Zombie" },
    { a: "Everclear", t: "Santa Monica" },
    { a: "Garbage", t: "Stupid Girl" },
    { a: "Cracker", t: "Low" },
    { a: "Blind Melon", t: "No Rain" },
    { a: "4 Non Blondes", t: "What's Up" },
    { a: "The Prodigy", t: "Firestarter" },
    { a: "The Offspring", t: "Self Esteem" },
    { a: "Alice in Chains", t: "Would?" },
    { a: "Soundgarden", t: "Spoonman" },
    { a: "Radiohead", t: "Karma Police" },
    { a: "Oasis", t: "Champagne Supernova" },
    { a: "James", t: "Laid" },
    { a: "New Order", t: "Regret" },
    { a: "Depeche Mode", t: "Policy of Truth" },
    { a: "Third Eye Blind", t: "Jumper" },
    { a: "Smash Mouth", t: "Walkin' on the Sun" },
    { a: "Cake", t: "The Distance" },
    { a: "Sublime", t: "Santeria" },
    { a: "Blink-182", t: "Dammit" },
    { a: "Harvey Danger", t: "Flagpole Sitta" },
    { a: "Semisonic", t: "Closing Time" },
    { a: "Toadies", t: "Possum Kingdom" },
    { a: "The Presidents of the United States of America", t: "Lump" },
    { a: "Silverchair", t: "Tomorrow" },
    { a: "Butthole Surfers", t: "Pepper" },
    { a: "Gin Blossoms", t: "Hey Jealousy" },
    { a: "Weezer", t: "Say It Ain't So" },
    { a: "Beck", t: "Where It's At" },
    { a: "Beastie Boys", t: "Intergalactic" },
    { a: "Pearl Jam", t: "Even Flow" },
    { a: "Nirvana", t: "Heart-Shaped Box" },
    { a: "Smashing Pumpkins", t: "Today" },
    { a: "R.E.M.", t: "Man on the Moon" },
    { a: "Nine Inch Nails", t: "Head Like a Hole" },
    { a: "Jesus Jones", t: "Right Here, Right Now" },
    { a: "EMF", t: "Unbelievable" },
    { a: "Concrete Blonde", t: "Joey" },
    { a: "Morrissey", t: "The More You Ignore Me, the Closer I Get" },
    { a: "Faith No More", t: "Midlife Crisis" },
    { a: "Primus", t: "Jerry Was a Race Car Driver" },
    { a: "Rancid", t: "Time Bomb" },
    { a: "The Breeders", t: "Cannonball" },
    { a: "Hole", t: "Celebrity Skin" },
    { a: "Bush", t: "Machinehead" },
    { a: "Foo Fighters", t: "My Hero" },
    { a: "Red Hot Chili Peppers", t: "Scar Tissue" },
    { a: "Third Eye Blind", t: "How's It Going to Be" },
    { a: "Lit", t: "My Own Worst Enemy" },
    { a: "Marilyn Manson", t: "The Beautiful People" },
    { a: "Korn", t: "Freak on a Leash" },
    { a: "Fatboy Slim", t: "The Rockafeller Skank" },
    { a: "Depeche Mode", t: "I Feel You" },
    { a: "Goo Goo Dolls", t: "Name" },
    { a: "No Doubt", t: "Don't Speak" },
    { a: "Smash Mouth", t: "All Star" },
    { a: "Blink-182", t: "All the Small Things" },
    { a: "Green Day", t: "Good Riddance (Time of Your Life)" },
    { a: "Stroke 9", t: "Little Black Backpack" },
  ] },
  { call: "WQCD", name: "CD101.9 NEW YORK", format: "SMOOTH JAZZ", tracks: [
    { a: "Kenny G", t: "Forever in Love" },
    { a: "Sade", t: "No Ordinary Love" },
    { a: "Boney James", t: "Sweet Thing" },
    { a: "Candy Dulfer and David A. Stewart", t: "Lily Was Here" },
    { a: "The Rippingtons", t: "Curves Ahead" },
    { a: "Fourplay", t: "Bali Run" },
    { a: "Dave Koz", t: "You Make Me Smile" },
    { a: "Peter White", t: "Caravan of Dreams" },
    { a: "Kenny G", t: "Sentimental" },
    { a: "Fourplay", t: "Between the Sheets" },
    { a: "Rick Braun", t: "Cadillac Slim" },
    { a: "Grover Washington Jr.", t: "Soulful Strut" },
    { a: "Norman Brown", t: "That's the Way Love Goes" },
    { a: "Marc Antoine", t: "Madrid" },
    { a: "Ronny Jordan", t: "So What" },
    { a: "Kenny G", t: "The Moment" },
    { a: "Craig Chaquico", t: "Acoustic Highway" },
    { a: "Joe Sample", t: "Did You Feel That?" },
    { a: "Paul Taylor", t: "Pleasure Seeker" },
    { a: "Art Porter", t: "Pocket City" },
    { a: "David Sanborn", t: "Bang Bang" },
    { a: "Ottmar Liebert", t: "Barcelona Nights" },
    { a: "Boney James", t: "Seduction" },
    { a: "Sade", t: "Cherish the Day" },
    { a: "Down to the Bone", t: "Staten Island Groove" },
    { a: "Us3", t: "Cantaloop (Flip Fantasia)" },
    { a: "Chuck Loeb", t: "The Music Inside" },
    { a: "Richard Elliot", t: "Chill Factor" },
    { a: "Brian Culbertson", t: "So Good" },
    { a: "Herb Alpert", t: "North on South St." },
    { a: "Najee", t: "Tokyo Blue" },
    { a: "Keiko Matsui", t: "Full Moon and the Shrine" },
    { a: "Incognito", t: "Always There" },
    { a: "Kenny G with Peabo Bryson", t: "By the Time This Night Is Over" },
    { a: "Anita Baker", t: "Body and Soul" },
    { a: "Basia", t: "Cruising for Bruising" },
    { a: "Oleta Adams", t: "Get Here" },
    { a: "Luther Vandross", t: "Here and Now" },
    { a: "Gerald Albright", t: "My, My, My" },
    { a: "Kirk Whalum", t: "All I Do" },
    { a: "Dave Koz", t: "Castle of Dreams" },
    { a: "The Rippingtons", t: "Sahara" },
    { a: "Peter White", t: "Midnight in Manhattan" },
    { a: "Warren Hill", t: "The Passion Theme" },
    { a: "Richard Elliot", t: "When a Man Loves a Woman" },
    { a: "Boney James", t: "Body Language" },
    { a: "Rick Braun", t: "Notorious" },
    { a: "Acoustic Alchemy", t: "Reference Point" },
    { a: "Lee Ritenour", t: "Wes Bound" },
    { a: "Phil Perry", t: "Call Me" },
    { a: "Jonathan Butler", t: "Do You Love Me?" },
    { a: "Candy Dulfer", t: "For the Love of You" },
    { a: "Bob James", t: "Joyride" },
    { a: "George Benson", t: "Love Remembers" },
    { a: "Spyro Gyra", t: "Heart of the Night" },
    { a: "Pat Metheny Group", t: "Always and Forever" },
    { a: "Jeff Lorber", t: "Midnight" },
    { a: "Chris Botti", t: "Midnight Without You" },
    { a: "Fourplay", t: "101 Eastbound" },
    { a: "Dave Koz", t: "Faces of the Heart" },
    { a: "Alex Bugnon", t: "107 in the Shade" },
    { a: "Kirk Whalum", t: "Cache" },
    { a: "The Jazzmasters", t: "Oceans Apart" },
    { a: "Incognito", t: "Don't You Worry 'Bout a Thing" },
    { a: "The Brand New Heavies", t: "Dream On Dreamer" },
    { a: "Swing Out Sister", t: "Am I the Same Girl" },
    { a: "Sade", t: "Kiss of Life" },
    { a: "Basia", t: "Drunk on Love" },
    { a: "Randy Crawford", t: "Give Me the Night" },
    { a: "Michael Franks", t: "Dragonfly Summer" },
    { a: "Vanessa Williams", t: "The Sweetest Days" },
    { a: "Toni Braxton", t: "Breathe Again" },
    { a: "Simply Red", t: "Stars" },
    { a: "Dave Koz", t: "Can't Let You Go (The Sha La Song)" },
    { a: "The Rippingtons", t: "Weekend in Monaco" },
    { a: "Acoustic Alchemy", t: "Jamaica Heartbeat" },
    { a: "Earl Klugh", t: "Sudden Burst of Energy" },
    { a: "Norman Brown", t: "Better Days Ahead" },
    { a: "Paul Taylor", t: "Til We Meet Again" },
    { a: "3rd Force", t: "Here Comes the Night" },
    { a: "Jesse Cook", t: "Tempest" },
    { a: "The Benoit Freeman Project", t: "After the Love Has Gone" },
    { a: "George Benson", t: "Standing Together" },
    { a: "Gato Barbieri", t: "Straight into the Sunrise" },
    { a: "Avenue Blue featuring Jeff Golub", t: "Nightlife" },
    { a: "Ken Navarro", t: "The Labor of Love" },
    { a: "Rick Braun", t: "Missing in Venice" },
    { a: "Richard Elliot", t: "Jumpin' Off" },
    { a: "Peter White", t: "Promenade" },
    { a: "Yellowjackets", t: "Greenhouse" },
    { a: "The Rippingtons", t: "Topaz" },
    { a: "Joe Sample", t: "Ashes to Ashes" },
    { a: "George Howard", t: "Love and Understanding" },
    { a: "Curtis Stigers", t: "I Wonder Why" },
    { a: "Doc Powell", t: "97th and Columbus" },
    { a: "Zachary Breaux", t: "Cafe Reggio" },
    { a: "Strunz and Farah", t: "Primal Magic" },
    { a: "Enya", t: "Caribbean Blue" },
    { a: "Nelson Rangell", t: "In Every Moment" },
    { a: "Herb Alpert", t: "Passion Dance" },
  ] },
];
